import type { Metadata } from "next";
import "../styles/globals.css"
import Navbar from "../components/Navbar"
import { Kanit } from "next/font/google";

const kanit = Kanit({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-kanit',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <Navbar />
        <main className="mt-[11rem]">
          {children}
        </main>
      </body>
    </html>
  );
}
